
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: raji@123@
  host: localhost
  port: 5432

development:
  <<: *default
  database: Chat_App_development

test:
  <<: *default
  database: Chat_App_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>